### PR TITLE
Create autosuggest.py

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hello @teolemon, I hope you are doing well. Can you describe what feature you want to add there?

**Comment by teolemon** [comment]
This returns some suggestions for the various facets of openfoodfacts
 "http://" + geography + ".openfoodfacts.org/cgi/suggest.pl?lc="+ language + "&tagtype=" + tag_type

For instance, to get suggestions for worldwide categories in French, (fr, fr, categories)

**Comment by frankrousseau** [comment]
Ok thx. I'm not allowed to merge it. So I let you do it.

**Comment by teolemon** [comment]
I just canceled and re-sent the invite

**Comment by frankrousseau** [comment]
I got the cancelation email but not the new invitation. It looks like Github don't like much Free emails.

**Comment by teolemon** [comment]
What about your spambox ?

**Comment by frankrousseau** [comment]
mmm... nothing. Let's fix this next Thursday.

**Pull request merged**
