### PR TITLE
Update README.md add instantiation of api

### PR DESCRIPTION
**Pull request by BrunoEVCosta**
Description of using program for the first time

## Description

- Brief note about the issue

## Solution

- Mention how your solution resolves the issue

## Related issue(s)

- Fixes #[ISSUE NUMBER]

### CODE REVIEW

**Comment by raphael0202** [comment]
Hello!
There is no need for this, as "v2" is already the default value.

**Comment by BrunoEVCosta** [comment]
> Hello! There is no need for this, as "v2" is already the default value.

Hi @raphael0202 as for the argument your right, how about with an empty argument ?

```  python 
api = openfoodfacts.API()

```

Just to have the bare min. in the ReadMe, as a means to test out the code before going into all the options.

**Comment by raphael0202** [comment]
I'm sorry I misread your PR, indeed the API() call was missing!

**Comment by raphael0202** [comment]
Thank you for your contribution! :)

**Pull request merged**
