### PR TITLE
fix: fixed search products by text

### LINKED ISSUE #190: Problem with product search, something is certainly hardcoded
### What
The App always return the result for "eau mineral" (I guess it's for this because it's always starting with cristaline)
which is basically making the API useless

### Steps to reproduce the behavior:
import openfoodfacts
api = openfoodfacts.API(version="v2")
results = api.product.text_search("Tomate")

### Expected behavior
Return products data that are in link with Tomate and not "mineral water"

### Platform (Desktop, Mobile, Hunger Games)
 - OS: MACOS
 - Platform MacBook AIR

### PR DESCRIPTION
**Pull request by Fedeton**
## Description

The `/api/v2/search` endpoint always returns the same results no matter what text is used.

## Solution

Looking at the main site (https://world.openfoodfacts.org) and the openfoodfacts-dart repository I noticed that both use this endpoint `/cgi/search.pl` which should work fine with the same parameters.

## Related issue(s)

- Fixes #190

### CODE REVIEW

**Comment by alexgarel** [comment]
@Fedeton thanks !

note:
- we are following [conventional commit](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary) (otherwise [check fail](https://github.com/openfoodfacts/openfoodfacts-python/actions/runs/7053022469/job/19199274951))

**Comment by alexgarel** [comment]
@Fedeton a quality check is failing, can you fix it ?

**Comment by Fedeton** [comment]
I'm sorry. Give me some time and than I try to fix it.

**Review by alexgarel — APPROVED** [review]
Thanks, that's indeed important !

**Comment by alexgarel** [comment]
Still failing @Fedeton !

**Comment by Fedeton** [comment]
I have made another commit, should I do something else or should I just wait?

**Comment by alexgarel** [comment]
@Fedeton still failing :-/ (were you able to run tests them locally ?)

> openfoodfacts/api.py:90: error: Incompatible types in assignment (expression has type "str", target has type "int")  [assignment]
> Found 1 error in 1 file (checked 15 source files)
> Error: Process completed with exit code 1.

**Comment by raphael0202** [comment]
@Fedeton can you update your branch with latest commit in develop?
mypy was temporarily failing on some commits in develop, but it's now fixed.

**Comment by Fedeton** [comment]
Hello, I have performed the following steps on my local repo:
1. `git remote add upstream https://github.com/openfoodfacts/openfoodfacts-python.git`
2. `git fetch upstream`
3. `git checkout develop`
4. `git rebase upstream/develop`
5. `git checkout product-search`
6. `git merge develop`
7. `git push`
Are these steps okay?

**Comment by alexgarel** [comment]
@Fedeton I invited you to our python team so next time you can start your branch directly on the project :-)

**Comment by alexgarel** [comment]
Thanks for your contribution :tada:

**Comment by Fedeton** [comment]
It was a pleasure, thanks to all of you for the support

**Pull request merged**
