### PR TITLE
fix: fix_upd_product

### LINKED ISSUE #181: Update a product does not work with code parameter
### What
In theory, according to the documentation (https://github.com/openfoodfacts/openfoodfacts-python/blob/develop/docs/usage.md), we can update products with 2 parameters. 

`results = api.product.update(CODE, body)`

In practice, a single parameter is accepted:
```
    results = api.product.update('8000300404425', body)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ProductResource.update() takes 2 positional arguments but 3 were given
```

### Steps to reproduce the behavior:
Try to update a product (in DEV!).

### Expected behavior
Need to update: https://github.com/openfoodfacts/openfoodfacts-python/blob/develop/openfoodfacts/api.py
This function exactly:
   ```
 def update(self, body: Dict[str, Any]):
        """Create a new product or create it if it doesn't exist yet."""
        if not body.get("code"):
            raise ValueError("missing code from body")

        url = f"{self.base_url}/cgi/product_jqm2.pl"
        return send_for_urlencoded_post_request(url, body, self.api_config)
```

Two options:
 - add code as parameter for that function (preferred option because documentation tells that and there is condition if not body.get("code"))
 - update documentation and the condition in the function

**Remark:** beside this bug, it is possible to update a product by providing only the body as parameter and put the code in the body itself.

We could rephrase that sentence, too:
"""Create a new product or create it if it doesn't exist yet."""

### PR DESCRIPTION
**Pull request by benbenben2**
## Description
Updated documentation only, to avoid doing additional devs.

## Related issue(s)

- Fixes #181

### CODE REVIEW

**Review by alexgarel — APPROVED** [review]
LGTM but I imagine it will conflict with @raphael0202 PR ?

**Comment by raphael0202** [comment]
@alexgarel indeed, but I've resolved the conflicts. Thank you @benbenben2!

**Comment by benbenben2** [comment]
You roll backed the changes for the README file @raphael0202 


> Screenshot_20231205_074739

**Comment by raphael0202** [comment]
@benbenben2 It's not really a rollback, I updated this part of the documentation as well on my PR and I chose this version instead!

**Pull request merged**
